services:
  random-generator:
    container_name: random-generator
    build: ./
    environment:
      OTEL_SERVICE_NAME: 'random-generator'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
      OTEL_EXPORTER_OTLP_PROTOCOL: 'http/protobuf'
      OTEL_LOGS_EXPORTER: 'otlp'
      OTEL_TRACES_EXPORTER: 'otlp'
      OTEL_METRICS_EXPORTER: 'otlp'
      OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED: "true"
      OTEL_INSTRUMENTATION_PROCESS_METRICS_ENABLED: "true"
    ports:
      - '8080:8080'
    depends_on:
      - otel-collector
    networks:
      - otel-network
 
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4318:4318"  # OTLP HTTP endpoint
      - "8889:8889"  # Prometheus scrape endpoint
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro  # Bind mount your config
    depends_on:
      - prometheus
    networks:
      - otel-network
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=1h
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - otel-network
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - otel-network  
  
      
networks:
  otel-network:
    driver: bridge