global:
  scrape_interval: 15s # How often to scrape targets (e.g. 15 seconds)

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Change port if your app runs on a different one